doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    WNCOrganizerBundle: ~
                    JMSPaymentCoreBundle: ~
                    
mopa_bootstrap:
  form:
    show_legend: false
    