parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     wnc_walktheland
    database_user:     root
    database_password: lukasz.123

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
    
    
    # Sonata Admin Options
    sonata_admin.title:             Walk The Land
    sonata_admin.logo_title:        /bundles/sonataadmin/logo_title.png
    sonata_media.cdn.host:          /uploads/media
    
    contact_email: tworzenieweb@gmail.com