sonata_user:
    security_acl:             false
    table:
        user_group:           fos_user_user_group

    admin:
      user:
        class: Application\Sonata\UserBundle\Admin\UserAdmin

    manager_type:             orm

    profile:
        form:
            type:                 application_sonata_user_edit
            handler:              sonata.user.profile.form.handler.default
            name:                 sonata_user_profile_form
            validation_groups:
                # Defaults:
                - Profile
                - Default