<?php

namespace WNC\Bundle\OrganizerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends EntityRepository
{
  
  public function getEnabledWithPhoto($type)
  {
    $dql = "SELECT p, b FROM WNCOrganizerBundle:Banner b INNER JOIN b.picture p WHERE b.enabled = :enabled and b.type = :type";
    return $this->getEntityManager()->createQuery($dql)
            ->setParameter('enabled', true)
            ->setParameter('type', $type)
            ->execute();
    
  }
  
}
