<?php

namespace WNC\Bundle\OrganizerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonateRepository extends EntityRepository
{
  
  public function getDonators()
  {
    
    $dql = 'SELECT d from WNCOrganizerBundle:Donate d';
    return $this->getEntityManager()->createQuery($dql)
            ->getResult('donateHydrator');
    
  }
  
}
