<?php

namespace WNC\Bundle\OrganizerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganizerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizerRepository extends EntityRepository
{
  
  private function withContact()
  {
    
    return $this->createQueryBuilder('o')
            ->select('o', 'c')
            ->innerJoin('o.contact', 'c');
    
  }
  
  public function findAllWithContact() {
    
    return $this->withContact()
            ->orderBy('o.name')
            ->getQuery()
            ->execute();
    
  }
  
  public function findOneBySlugWithContact($slug)
  {
    return $this->withContact()
            ->where('o.slug = ?1')
            ->setParameter('1', $slug)
            ->getQuery()
            ->getSingleResult();
  }
  
}
